### ISSUE TITLE
Having trouble compiling with PyBOMBS

### ISSUE THREAD

**Issue by cafeclimber** [osh/gr-eventstream#20]
I saw someone else have a similar error with [gr-dsd](https://github.com/argilo/gr-dsd/issues/12). Wondering if there's a fix
```
PyBOMBS - INFO - PyBOMBS Version 2.3.1a
PyBOMBS.install_manager - INFO - Phase 1: Creating install tree and installing binary packages:
Install tree:
|
\- gr-eventstream
PyBOMBS.install_manager - INFO - Phase 2: Recursively installing source packages to prefix:
PyBOMBS.install_manager - INFO - Installing package: gr-eventstream
PyBOMBS.Fetcher - INFO - Already fetched: gr-eventstream
PyBOMBS.Packager.source - WARNING - Build dir already exists: /home/cafeclimber/sdr/src/gr-eventstream/build
Configuring: (100%) [========================================================]
PyBOMBS.Packager.source - WARNING - Configuration failed. Re-trying with higher verbosity.
-- Building Static Libraries: OFF
Checking for GNU Radio Module: RUNTIME
 * INCLUDES=/home/cafeclimber/sdr/include
 * LIBS=/lib64/libgnuradio-runtime.so;/lib64/libgnuradio-pmt.so
GNURADIO_RUNTIME_FOUND = TRUE
Checking for GNU Radio Module: BLOCKS
 * INCLUDES=/home/cafeclimber/sdr/include
 * LIBS=/lib64/libgnuradio-blocks.so;/lib64/libgnuradio-runtime.so;/lib64/libgnuradio-pmt.so
GNURADIO_BLOCKS_FOUND = TRUE
Checking for GNU Radio Module: PMT
 * INCLUDES=/home/cafeclimber/sdr/include
 * LIBS=/lib64/libgnuradio-runtime.so;/lib64/libgnuradio-pmt.so
GNURADIO_PMT_FOUND = TRUE
-- GR_CTRLPORT ON.

-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   system
--   date_time
--   program_options
--   thread
--   regex
--   chrono
--   atomic
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   unit_test_framework
-- 
-- Checking for module SWIG
-- Found SWIG version 3.0.11.
  File "<string>", line 3
    print sysconfig.get_python_lib(plat_specific=True, prefix='')
                  ^
SyntaxError: invalid syntax
CMake Error at /home/cafeclimber/sdr/lib/cmake/gnuradio/GrPython.cmake:113 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.
Call Stack (most recent call first):
  /home/cafeclimber/sdr/lib/cmake/gnuradio/GrSwig.cmake:25 (include)
  swig/CMakeLists.txt:6 (INCLUDE)


-- Found PythonLibs: /usr/lib64/libpython3.6m.so (found suitable version "3.6.0", minimum required is "2") 
Traceback (most recent call last):
  File "<string>", line 2, in <module>
TypeError: Unicode-objects must be encoded before hashing
CMake Error at /home/cafeclimber/sdr/lib/cmake/gnuradio/UseSWIG.cmake:199 (add_executable):
  add_executable called with incorrect number of arguments
Call Stack (most recent call first):
  /home/cafeclimber/sdr/lib/cmake/gnuradio/UseSWIG.cmake:256 (SWIG_ADD_SOURCE_TO_MODULE)
  /home/cafeclimber/sdr/lib/cmake/gnuradio/GrSwig.cmake:192 (SWIG_ADD_MODULE)
  swig/CMakeLists.txt:34 (GR_SWIG_MAKE)


You have called ADD_LIBRARY for library _es_swig without any source files. This typically indicates a problem with your CMakeLists.txt file
Traceback (most recent call last):
  File "<string>", line 2, in <module>
TypeError: Unicode-objects must be encoded before hashing
Traceback (most recent call last):
  File "<string>", line 2, in <module>
TypeError: Unicode-objects must be encoded before hashing
CMake Error at /home/cafeclimber/sdr/lib/cmake/gnuradio/GrPython.cmake:125 (add_custom_target):
  add_custom_target cannot create target "ALL" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory
  "/home/cafeclimber/sdr/src/gr-eventstream/swig".  See documentation for
  policy CMP0002 for more details.
Call Stack (most recent call first):
  /home/cafeclimber/sdr/lib/cmake/gnuradio/GrPython.cmake:228 (GR_UNIQUE_TARGET)
  swig/CMakeLists.txt:43 (GR_PYTHON_INSTALL)


-- 
-- Checking for module SWIG
-- Found SWIG version 3.0.11.
-- Found PythonLibs: /usr/lib64/libpython3.6m.so (found version "3.6.0") 
  File "<string>", line 3
    print sysconfig.get_python_lib(plat_specific=True, prefix='')
                  ^
SyntaxError: invalid syntax
CMake Error at /home/cafeclimber/sdr/lib/cmake/gnuradio/GrPython.cmake:113 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.
Call Stack (most recent call first):
  /home/cafeclimber/sdr/lib/cmake/gnuradio/GrSwig.cmake:25 (include)
  python/CMakeLists.txt:6 (INCLUDE)


Traceback (most recent call last):
  File "<string>", line 2, in <module>
TypeError: Unicode-objects must be encoded before hashing
CMake Error at /home/cafeclimber/sdr/lib/cmake/gnuradio/GrPython.cmake:125 (add_custom_target):
  add_custom_target cannot create target "ALL" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory
  "/home/cafeclimber/sdr/src/gr-eventstream/swig".  See documentation for
  policy CMP0002 for more details.
Call Stack (most recent call first):
  /home/cafeclimber/sdr/lib/cmake/gnuradio/GrPython.cmake:228 (GR_UNIQUE_TARGET)
  python/CMakeLists.txt:9 (GR_PYTHON_INSTALL)


-- Using install prefix: /home/cafeclimber/sdr
-- Configuring incomplete, errors occurred!
See also "/home/cafeclimber/sdr/src/gr-eventstream/build/CMakeFiles/CMakeOutput.log".
See also "/home/cafeclimber/sdr/src/gr-eventstream/build/CMakeFiles/CMakeError.log".
PyBOMBS.Packager.source - ERROR - Configuration failed after running at least twice.
PyBOMBS.Packager.source - ERROR - Problem occurred while building package gr-eventstream:
Configuration failed
PyBOMBS.install_manager - ERROR - Error installing package gr-eventstream. Aborting.
```

**Comment by osh** [comment]
Hrm, I haven't see this one before --- what OS are you running?

**Comment by cafeclimber** [comment]
Running Arch Linux:
    Kernel: 4.9.8
    Python:  2.7.13 / 3.6.0
    PyBombs: 2.3.0

I've tried completely removing the source, uninstalling pybombs, removing all config directories, ensuring binaries from my distro for anything gnuradio aren't present, then reinstalling, and I still get the same error. 

I have also tried manually cloning the source, going making a build directory and running cmake, resulting in the same error.

Finally, I've also tried using gr_modtool to create a new module and pull the source in and compile again but still get the same error 🙁

**Comment by osh** [comment]
GNU Radio support for Python 3 is still very new -- I suspect that is the root of this issue, perhaps trying with python 2 would go smoother --

**Comment by cafeclimber** [comment]
Hmm. I had tried to be very specific with my latest pybombs install in trying to use Python 2's pip, but now that you mention it, I can see it was getting Python 3 libs...Will let you know if that's it. Thanks for the help

**Comment by cafeclimber** [comment]
I'm very unclear on how to force cmake or pybombs to use Python 2's interpreter and libraries. Any thoughts?

**Comment by cafeclimber** [comment]
Whew. Okay I managed to get it working by doing the following:
    * Cloning
    * Making build directory, attempting to build, and letting it fail
    * Editing the resulting CMakeCache.txt file by replacing instances of python with python2.7 and python3.6m with python2.7
    * Running pybombs install gr-eventstream

If I knew how to make this a permanent change, I would definitely make a pull request but this is such a hack

**Comment by osh** [comment]
closing until a proper pull request is provided - 
This seems like a Pybombs / GNU Radio problem with checking the proper python version
